/**
 * Content model for the Silverback site.
 *
 * Every user-facing string lives here. The actual values used by the site are
 * exported from '$lib/data/notion-content' — a file generated by
 * scripts/fetch-notion-content.js from Notion databases. When Notion is not
 * configured (or a fetch fails) the generator falls back to the defaults
 * below, so the build always works.
 */

export interface SiteInfo {
	tagline: string;
	subline: string;
	stars: string;
	showActivity: boolean;
}

export interface Stat {
	value: string;
	label: string;
}

export interface Principle {
	n: string;
	title: string;
	body: string;
}

export interface Repo {
	name: string;
	lang: string;
	desc: string;
	stars: string;
	forks: string;
	updated: string;
	url?: string;
}

export interface ActivityItem {
	who: string;
	what: string;
	repo: string;
	when: string;
}

export interface TimelineEntry {
	year: string;
	text: string;
}

export interface GovernanceRule {
	n: string;
	title: string;
	body: string;
}

export interface Maintainer {
	initials: string;
	name: string;
	role: string;
}

export interface Step {
	n: string;
	title: string;
	body: string;
	link: string;
}

export interface Issue {
	title: string;
	repo: string;
	label: string;
}

export interface Channel {
	name: string;
	body: string;
	meta: string;
}

export interface Post {
	kind: string;
	title: string;
	excerpt: string;
	date: string;
}

export interface Tagline {
	n: string;
	line: string;
	note: string;
}

export interface FooterCol {
	title: string;
	links: string[];
}

export interface SiteContent {
	site: SiteInfo;
	/** Free-form page copy, keyed by section. */
	copy: Record<string, string>;
	stats: Stat[];
	principles: Principle[];
	repos: Repo[];
	activity: ActivityItem[];
	timeline: TimelineEntry[];
	governance: GovernanceRule[];
	maintainers: Maintainer[];
	steps: Step[];
	issues: Issue[];
	channels: Channel[];
	posts: Post[];
	taglines: Tagline[];
	footerCols: FooterCol[];
}

export const defaultContent: SiteContent = {
	site: {
		tagline: 'Strength in the open.',
		subline:
			'A collective of engineers maintaining the unglamorous infrastructure other people build on. Forty-two repositories, one licence, no gatekeepers.',
		stars: '12.4k',
		showActivity: true
	},

	copy: {
		home_hero_kicker: 'Open-source collective · est. 2019',
		home_hero_primary: 'Start contributing',
		home_hero_secondary: 'Browse projects',
		home_principles_kicker: 'What we stand for',
		home_principles_title: 'Three rules,\nheld without exception.',
		home_featured_kicker: 'Featured work',
		home_featured_title: 'Nine projects. No monoliths.',
		home_featured_all: 'All repositories →',
		home_activity_kicker: 'Live activity',
		home_activity_title: 'The last 24 hours.',
		home_activity_body:
			'Everything you see here happened in the open. Nothing is staged behind a private fork.',
		home_cta_title: 'Your first patch\ncan land this week.',
		home_cta_body:
			'Every repository keeps a curated set of first issues, a reviewer on rotation, and a hard promise: no patch waits longer than 72 hours for a human answer.',
		home_cta_primary: 'Read the contributor guide →',
		home_cta_secondary: 'How we govern ourselves →',

		about_kicker: 'About the community',
		about_hero_title: 'A silverback does not need to raise its voice to lead the troop.',
		about_hero_body:
			'Silverback is a collective of 1,830 engineers maintaining infrastructure that other people\u2019s work depends on. We are deliberately unglamorous: no conference circuit, no growth targets, no venture money. Just tools that hold under load, and a community that behaves like adults.',
		about_history_title: 'How we got here',
		about_governance_title: 'Governance',
		about_governance_body: 'Fourteen maintainers, one written constitution, zero managers.',
		about_maintainers_title: 'Maintainers',

		projects_kicker: 'Repositories · 8 public',
		projects_title: 'Small tools that refuse to become platforms.',

		contribute_kicker: 'Contribute',
		contribute_title: 'Join the troop.',
		contribute_body:
			'You do not need permission, an invitation, or a track record. You need a small, well-argued change and the patience to see it reviewed.',
		contribute_issues_title: 'Good first issues',
		contribute_issues_updated: 'Updated 6 minutes ago',
		contribute_talk_title: 'Where we talk',
		contribute_talk_body:
			'Asynchronous by default. Nothing important is decided in a voice call. Silverback coordination moves to Buzz — humans and agents in the same signed rooms.',

		updates_kicker: 'Updates',
		updates_title: 'Release notes, RFCs and the occasional opinion.',
		updates_featured_kicker: 'Maintainer note · 18 Jul 2026',
		updates_featured_title: 'Why we froze the API surface for a year',
		updates_featured_excerpt:
			'Twelve months without a breaking change was the least popular decision we ever made, and the reason adoption tripled. A post-mortem on saying no.',
		updates_featured_cta: 'Read the note →',

		foundations_kicker: 'Design foundations',
		foundations_title: 'Monoline, high contrast, nothing decorative.',
		foundations_body:
			'The system is drawn from the mark itself: one weight of line, sharp corners, generous air, and a single silver tone doing all the softening. Anything that cannot be justified as structure gets removed.',
		foundations_palette_title: 'Palette',
		foundations_type_title: 'Type',
		foundations_type_body:
			'Space Grotesk for everything human. JetBrains Mono for anything a machine produced: labels, counts, timestamps, repo names.',
		foundations_components_title: 'Components',
		foundations_taglines_title: 'Taglines',
		foundations_taglines_body:
			'The live hero line, ranked for tone: short, declarative, no exclamation marks.',
		foundations_mobile_title: 'Mobile homepage',
		foundations_mobile_body:
			'390pt. Single column, 24px gutters, logo stacked above the line, stats become a 2×2 hairline grid, nav collapses to mark + menu.',

		footer_blurb:
			'Infrastructure built in public since 2019. Governed by its maintainers, funded by its users, owned by nobody.',
		footer_copyright: '© 2026 Silverback Collective · MIT licensed'
	},

	stats: [
		{ value: '8', label: 'Repositories' },
		{ value: '1,830', label: 'Contributors' },
		{ value: '12.4k', label: 'Stars' },
		{ value: 'MIT', label: 'Licence' }
	],

	principles: [
		{
			n: '01',
			title: 'Open by default',
			body: 'Every RFC, roadmap and post-mortem lives in public. There is no private repository where the real decisions happen.'
		},
		{
			n: '02',
			title: 'Built to be read',
			body: 'Code is a document. We optimise for the person who inherits it, not the person who wrote it at 2am.'
		},
		{
			n: '03',
			title: 'Slow releases, fast fixes',
			body: 'Minor versions land quarterly. Security patches land the same day. Stability is a feature we refuse to trade.'
		}
	],

	repos: [
		{
			name: 'lampo.rs',
			lang: 'Rust',
			desc: 'An experimental implementation of a tiny Lightning node — lampo is lightning in Italian.',
			stars: '64',
			forks: '26',
			updated: '2w ago',
			url: 'https://github.com/vincenzopalazzo/lampo.rs'
		},
		{
			name: 'bitchat-to-sonar',
			lang: 'Swift',
			desc: 'Sonar: sense who is nearby before you see them. Bluetooth peer discovery as a feature, not plumbing.',
			stars: '2',
			forks: '2',
			updated: 'Today',
			url: 'https://github.com/hedwig-corp/bitchat-to-sonar'
		},
		{
			name: 'cdk-ldk-server-processor',
			lang: 'Rust',
			desc: 'CDK gRPC payment processor backed by an external ldk-server daemon.',
			stars: '0',
			forks: '0',
			updated: 'Today',
			url: 'https://github.com/vincenzopalazzo/cdk-ldk-server-processor'
		},
		{
			name: 'bitchat',
			lang: 'Swift',
			desc: 'Bluetooth mesh chat with IRC vibes — iOS and macOS client.',
			stars: '0',
			forks: '1',
			updated: 'Today',
			url: 'https://github.com/vincenzopalazzo/bitchat'
		},
		{
			name: 'bitchat-android',
			lang: 'Kotlin',
			desc: 'Bluetooth mesh chat with IRC vibes — Android client.',
			stars: '0',
			forks: '0',
			updated: 'Today',
			url: 'https://github.com/vincenzopalazzo/bitchat-android'
		},
		{
			name: 'cashu-wallet',
			lang: 'Swift',
			desc: 'Cashu ecash wallet for iOS and Android.',
			stars: '0',
			forks: '0',
			updated: 'Today',
			url: 'https://github.com/vincenzopalazzo/cashu-wallet'
		},
		{
			name: 'sentinel',
			lang: 'TypeScript',
			desc:
				'Continuous multi-harness AI security scanning for Bitcoin and Lightning — Loupe, redteam, VVAH, codecrucible, triage, spend stewardship.',
			stars: '0',
			forks: '0',
			updated: 'Today',
			url: 'https://github.com/hedwig-corp/sentinel'
		},
		{
			name: 'buzz',
			lang: 'Rust',
			desc:
				'Sovereign workspace where humans and agents share rooms, identity, and audit trail — community home for Silverback ops.',
			stars: '0',
			forks: '0',
			updated: 'Today',
			url: 'https://github.com/vincenzopalazzo/buzz'
		},
		{
			name: 'lnproof.space',
			lang: 'In the lab',
			desc: 'Not public yet — watch this space.',
			stars: '—',
			forks: '—',
			updated: 'Soon'
		}
	],

	activity: [
		{
			who: 'VP',
			what: 'Listed Sentinel under Silverback and drafted Buzz community ops for triage',
			repo: 'sentinel',
			when: 'Today'
		},
		{
			who: 'VP',
			what: 'Merged: share sheet — pick a recipient instead of broadcasting to the mesh',
			repo: 'bitchat-to-sonar #447',
			when: '1 hr'
		},
		{
			who: 'VP',
			what: 'Opened PR: wallet-gate escape path and bounded listener sync',
			repo: 'lampo.rs',
			when: '1 hr'
		},
		{
			who: 'VP',
			what: 'Fixed silent gRPC bind conflicts with a startup self-check',
			repo: 'cdk-ldk-server-processor',
			when: '2 hr'
		},
		{
			who: 'VP',
			what: 'Stopped iOS nearby peers flapping out of Sonar discovery',
			repo: 'bitchat-to-sonar #444',
			when: '2 hr'
		},
		{
			who: 'VP',
			what: 'Added a get_settings smoke-test client',
			repo: 'cdk-ldk-server-processor',
			when: '15 hr'
		}
	],

	timeline: [
		{
			year: '2019',
			text: 'Four maintainers fork an abandoned build tool because their employer will not upstream the fix.'
		},
		{
			year: '2021',
			text: 'The constitution is written: consensus over hierarchy, public over private, small over general.'
		},
		{
			year: '2023',
			text: 'Core passes one million weekly installs. The team turns down its first acquisition conversation.'
		},
		{
			year: '2025',
			text: 'Funding moves entirely to an open collective. Every expense is published monthly.'
		},
		{ year: '2026', text: 'Sentinel joins the troop: continuous Bitcoin security scanning, coordinated on Buzz, funded as a public good.' }
	],

	governance: [
		{
			n: 'Rule 01',
			title: 'Consensus, then a vote',
			body: 'Anyone may open an RFC. It stays open for fourteen days. Maintainers vote in public; dissent is recorded, not deleted.'
		},
		{
			n: 'Rule 02',
			title: 'Two reviewers, always',
			body: 'Nothing merges on one pair of eyes — including the founders\u2019 patches. Especially the founders\u2019 patches.'
		},
		{
			n: 'Rule 03',
			title: 'Rotating stewardship',
			body: 'Each repository has a steward for one quarter. The role rotates whether or not anyone wants it to.'
		},
		{
			n: 'Rule 04',
			title: 'Sunset without drama',
			body: 'A project with no steward for two quarters is archived with a written note. Abandonment is not a status we pretend about.'
		}
	],

	maintainers: [
		{ initials: 'NR', name: 'Nadia Rekic', role: 'core · scheduler' },
		{ initials: 'KA', name: 'Kwame Adeyemi', role: 'forge · CI' },
		{ initials: 'TM', name: 'Tomas Møller', role: 'atlas · topology' },
		{ initials: 'JD', name: 'June Delacroix', role: 'plinth · crypto' },
		{ initials: 'LS', name: 'Lina Sørensen', role: 'docs · onboarding' },
		{ initials: 'AV', name: 'Arjun Venkat', role: 'quiet · telemetry' },
		{ initials: 'MO', name: 'Mei Ono', role: 'canopy · data' },
		{ initials: 'GB', name: 'Gabriel Braun', role: 'security · response' }
	],

	steps: [
		{
			n: 'Step 01',
			title: 'Read the ground rules',
			body: 'Ten minutes, one page. It covers commit hygiene, how we argue, and what happens when we disagree.',
			link: 'CONTRIBUTING.md'
		},
		{
			n: 'Step 02',
			title: 'Take a first issue',
			body: 'Every repository keeps five issues scoped for a newcomer, with an assigned reviewer named up front.',
			link: 'Browse 34 open issues'
		},
		{
			n: 'Step 03',
			title: 'Open a small patch',
			body: 'Small is not a suggestion. Under 200 lines gets reviewed in a day; a thousand-line patch gets read in a week.',
			link: 'How review works'
		}
	],

	issues: [
		{
			title: 'Cache keys silently collide when two targets share an output path',
			repo: 'core',
			label: 'good first issue'
		},
		{
			title: 'Document the difference between a steward and a maintainer',
			repo: 'docs',
			label: 'docs'
		},
		{ title: 'Add a --dry-run flag to the topology importer', repo: 'atlas', label: 'good first issue' },
		{
			title: 'Error message for a missing toolchain names the wrong file',
			repo: 'forge',
			label: 'papercut'
		},
		{
			title: 'Constant-time comparison helper needs a fuzz target',
			repo: 'plinth',
			label: 'help wanted'
		}
	],

	channels: [
		{
			name: 'Buzz · Sentinel',
			body: 'Human + agent rooms for fleet ops, triage, and disclosure discipline. Buzz is the coordination plane; the VPS remains the scanner.',
			meta: 'Community workspace · self-hosted'
		},
		{
			name: 'Discussions',
			body: 'Long-form questions, design debate, and every RFC thread. Searchable forever.',
			meta: 'GitHub · 40 posts this week'
		},
		{
			name: 'Matrix',
			body: 'Synchronous when it has to be. Logged publicly, no decisions made here.',
			meta: '#silverback:matrix.org'
		},
		{
			name: 'Office hours',
			body: 'Two maintainers, one hour, every Thursday. Bring a broken branch.',
			meta: 'Thu 15:00 UTC'
		},
		{
			name: 'Mailing list',
			body: 'One digest a month: releases, RFC outcomes, and what we got wrong.',
			meta: '9,400 subscribers'
		}
	],

	posts: [
		{
			kind: 'Security',
			title: 'Sentinel and the AI security reckoning',
			excerpt:
				'After the COLDCARD / AI security conversation went public, continuous multi-harness defense stopped being optional. Sentinel is how Silverback answers — with triage, spend caps, and a Buzz room for humans and agents.',
			date: '5 Aug 2026'
		},
		{
			kind: 'Release',
			title: 'Forge 3.0: fewer concepts, faster builds',
			excerpt:
				'We deleted two thirds of the configuration surface. Here is what replaced it, and how to migrate in an afternoon.',
			date: '30 Jun 2026'
		},
		{
			kind: 'Community',
			title: 'Running governance with fourteen maintainers and no manager',
			excerpt:
				'What actually happens when consensus fails, written down honestly rather than aspirationally.',
			date: '12 Jun 2026'
		},
		{
			kind: 'Guide',
			title: 'A field guide to reviewing your first patch',
			excerpt:
				'Reviewing is a skill we teach badly across the whole ecosystem. A checklist we use internally.',
			date: '28 May 2026'
		},
		{
			kind: 'Post-mortem',
			title: 'The forty-minute CVE',
			excerpt:
				'A timeline of the plinth disclosure, including the ninety minutes we wasted before anyone paged a human.',
			date: '09 May 2026'
		},
		{
			kind: 'RFC',
			title: 'RFC 0028 outcome: no plugin marketplace',
			excerpt:
				'The most requested feature of the year, declined. The reasoning, and the dissenting notes in full.',
			date: '21 Apr 2026'
		}
	],

	taglines: [
		{
			n: '01',
			line: 'Strength in the open.',
			note: 'Recommended. Ties the mark to the licence model in four words.'
		},
		{
			n: '02',
			line: 'Quiet software. Heavy lifting.',
			note: 'Best for a technical audience; leans on understatement.'
		},
		{
			n: '03',
			line: 'Built in the open, built to last.',
			note: 'Warmest option. Reads well next to a governance page.'
		},
		{
			n: '04',
			line: 'Open source with a spine.',
			note: 'Sharpest. Use if the community wants to sound opinionated.'
		},
		{
			n: '05',
			line: 'The calm at the centre of your stack.',
			note: 'Positions the tools rather than the community.'
		},
		{
			n: '06',
			line: 'Lead quietly. Ship deliberately.',
			note: 'Doubles as the contributor-culture headline.'
		}
	],

	footerCols: [
		{ title: 'Projects', links: ['lampo.rs', 'bitchat', 'Sonar', 'Sentinel', 'Buzz', 'Cashu Wallet', 'All repositories'] },
		{
			title: 'Community',
			links: ['Contribute', 'Governance', 'Maintainers', 'Office hours', 'Code of conduct']
		},
		{
			title: 'Resources',
			links: ['Documentation', 'RFC archive', 'Updates', 'Open collective', 'Press kit']
		}
	]
};