/**
 * Auto-generated site content from Notion
 * DO NOT EDIT MANUALLY - this file is generated by scripts/fetch-notion-content.js
 *
 * The website never calls Notion at runtime; content is baked in at sync time.
 *
 * Last fetched: 2026-07-26T14:34:44.367Z
 * Sources: site=defaults, copy=defaults, stats=defaults, principles=defaults, repos=defaults, activity=defaults, timeline=defaults, governance=defaults, maintainers=defaults, steps=defaults, issues=defaults, channels=defaults, posts=defaults, taglines=defaults, footerCols=defaults
 */

import { defaultContent, type SiteContent } from '$lib/content';

export const content: SiteContent = {
	site: defaultContent.site,
	copy: defaultContent.copy,
	stats: defaultContent.stats,
	principles: defaultContent.principles,
	repos: defaultContent.repos,
	activity: defaultContent.activity,
	timeline: defaultContent.timeline,
	governance: defaultContent.governance,
	maintainers: defaultContent.maintainers,
	steps: defaultContent.steps,
	issues: defaultContent.issues,
	channels: defaultContent.channels,
	posts: defaultContent.posts,
	taglines: defaultContent.taglines,
	footerCols: defaultContent.footerCols
};
